

trigger:
- master
- develop

pool:
  vmImage: ubuntu-20.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(versionSpec)
  displayName: Install node

- script: npm install -g npm@$(npmVersion)
  displayName: Upgrade npm

# install dependencies
- script: npm install
  displayName: npm install

# build
- script: npm run build
  displayName: npm run build

# - script: npm run units
#   displayName: Run unit tests

# # For CI runs on master, automatically publish packages
# - bash: |
#       echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
#       cd _build
#       npm publish || true # Ignore publish failures, usually will happen because package already exists
#   displayName: npm publish
#   condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), eq(variables['build.sourcebranchname'], 'master'))
#   env:
#     NPM_TOKEN: $(npmPublishToken)
